id: P004150
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17932
  title: ཤེར་ཕྱིན་མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་དོན་གསལ།
  author: ''
  volumes:
    82f0f92f84814ec19239a39d4ee6515c:
      image_group_id: I8LS17942
      title: ''
      volume_number: 1
      total_pages: 682
      base_file: v001.txt
